import React, { useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, GripVertical, MapPin, Plus, Trash2, UserRoundCheck } from 'lucide-react';
import { addAdvisor, Assignment, Branch, loadRound, moveAdvisor, nextAdvisor, nudgeAdvisor, overrideAssignment, reassignBusy, removeAdvisor, RoundArea, RoundState, setActiveBranch, updateAdvisor } from '../services/roundService';
import { queueAssignmentUpdate } from '../services/registrationService';

export function RoundPanel({ onClose }: { onClose: () => void }) {
  const [state, setState] = useState<RoundState>(loadRound);
  const [name, setName] = useState(''); const [area, setArea] = useState<RoundArea>('Tradicional');
  const [returning, setReturning] = useState<Assignment | null>(null);
  const [returnAdvisorId, setReturnAdvisorId] = useState('');
  const [returnObservation, setReturnObservation] = useState('');
  const [busyObservation, setBusyObservation] = useState('');
  const [draggedId, setDraggedId] = useState('');
  const refresh = (next: RoundState) => setState({ ...next });
  const latest = state.assignments.filter(item => item.branch === state.activeBranch).at(-1);
  const branchAssignments = state.assignments.filter(item => item.branch === state.activeBranch);
  const currentAssignments = branchAssignments.filter((item, index, all) => all.map(candidate => candidate.visitId).lastIndexOf(item.visitId) === index).slice(-8).reverse();
  const ordered = (kind: RoundArea) => state.queues[state.activeBranch][kind].map(id => state.advisors.find(a => a.id === id)).filter(Boolean);
  return <main className="round-page">
    <div className="round-toolbar"><button className="round-back" onClick={onClose}><ArrowLeft size={18}/> Volver al derivador</button><div><span className="round-kicker">Control de recepción</span><h1>¿Cómo va la ronda?</h1></div><label className="branch-picker"><MapPin size={18}/><span>Sucursal</span><select value={state.activeBranch} onChange={e => refresh(setActiveBranch(e.target.value as Branch))}><option value="Jujuy">Jujuy</option><option value="Salta">Salta</option></select></label></div>
    <section className="round-next-grid">
      {(['Tradicional', 'Planes'] as RoundArea[]).map(kind => { const next = nextAdvisor(kind, state); return <article className="round-next" key={kind}><span>{kind === 'Tradicional' ? 'Venta tradicional' : 'Planes de ahorro'}</span><strong>{next?.name || 'Sin asesor disponible'}</strong><small>Próximo en recibir</small></article>; })}
    </section>
    {latest && <section className="round-card active-assignment"><div><span className="round-kicker">Atención más reciente</span><h2>{latest.advisorName}</h2><p>{latest.area} · {latest.status}</p></div><div className="assignment-actions"><div className="busy-reassign"><input aria-label="Observación del cambio de asesor" value={busyObservation} onChange={e => setBusyObservation(e.target.value)} maxLength={180} placeholder="Observación (opcional)"/><button className="busy-action" onClick={() => { const result = reassignBusy(latest.id, busyObservation); refresh(result.state); if (result.assignment) queueAssignmentUpdate(result.assignment.visitId, result.assignment.area, { id: result.assignment.advisorId, name: result.assignment.advisorName }, 'Asesor ocupado', busyObservation, result.assignment.branch); setBusyObservation(''); }}>Está ocupado: rederivar</button></div></div></section>}
    <section className="round-card">
      <h2>Equipo y orden · {state.activeBranch}</h2><p>Arrastrá los asesores para cambiar el orden. En tablet también podés usar las flechas. Marcá “Ocupado” cuando no pueda recibir.</p>
      <div className="round-teams">{(['Tradicional', 'Planes'] as RoundArea[]).map(kind => <div key={kind}><h3>{kind === 'Tradicional' ? 'Venta tradicional' : 'Planes de ahorro'}</h3>
        {ordered(kind).length === 0 && <div className="round-empty">Agregá el primer asesor de {state.activeBranch}.</div>}
        {ordered(kind).map((advisor, index) => { const a = advisor!; return <div className="advisor-row" draggable onDragStart={() => setDraggedId(a.id)} onDragOver={e => e.preventDefault()} onDrop={() => { if (draggedId) refresh(moveAdvisor(draggedId, a.id)); setDraggedId(''); }} key={a.id}><GripVertical className="drag-handle" size={19}/><UserRoundCheck size={20}/><span><small>{index + 1}</small>{a.name}</span><div className="order-buttons"><button disabled={index === 0} aria-label={`Subir a ${a.name}`} onClick={() => refresh(nudgeAdvisor(a.id, -1))}><ArrowUp size={15}/></button><button disabled={index === ordered(kind).length - 1} aria-label={`Bajar a ${a.name}`} onClick={() => refresh(nudgeAdvisor(a.id, 1))}><ArrowDown size={15}/></button></div><label className="busy-toggle"><input type="checkbox" checked={a.busy} onChange={e => refresh(updateAdvisor(a.id, { busy: e.target.checked }))}/><span>{a.busy ? 'Ocupado' : 'Disponible'}</span></label><button aria-label={`Eliminar a ${a.name}`} onClick={() => refresh(removeAdvisor(a.id))}><Trash2 size={17}/></button></div>; })}
      </div>)}</div>
      <form className="add-advisor" onSubmit={e => { e.preventDefault(); if (!name.trim()) return; refresh(addAdvisor(name, area)); setName(''); }}><input aria-label="Nombre del asesor" value={name} onChange={e => setName(e.target.value)} placeholder="Nombre del asesor"/><select aria-label="Área" value={area} onChange={e => setArea(e.target.value as RoundArea)}><option value="Tradicional">Venta tradicional</option><option value="Planes">Planes de ahorro</option></select><button><Plus size={18}/> Agregar</button></form>
    </section>
    {returning && <section className="round-card return-attention"><div><span className="round-kicker">Devolución excepcional</span><h2>Atención de {returning.advisorName}</h2><p>Elegí quién debe retomarla. La ronda normal no cambiará.</p></div><label>Asesor que retoma<select value={returnAdvisorId} onChange={e => setReturnAdvisorId(e.target.value)}><option value="">Seleccionar…</option>{state.advisors.filter(a => a.branch === returning.branch && a.area === returning.area).map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Constancia<textarea value={returnObservation} onChange={e => setReturnObservation(e.target.value)} maxLength={180} placeholder="Ej.: devolución solicitada por el jefe…"/></label><div className="return-buttons"><button onClick={() => { setReturning(null); setReturnAdvisorId(''); setReturnObservation(''); }}>Cancelar</button><button disabled={!returnAdvisorId || !returnObservation.trim()} onClick={() => { const result = overrideAssignment(returning.id, returnAdvisorId, returnObservation); refresh(result.state); if (result.assignment) queueAssignmentUpdate(result.assignment.visitId, result.assignment.area, { id: result.assignment.advisorId, name: result.assignment.advisorName }, 'Pedido del jefe', returnObservation, result.assignment.branch); setReturning(null); setReturnAdvisorId(''); setReturnObservation(''); }}>Guardar devolución</button></div></section>}
    <section className="round-card"><h2>Últimas atenciones · {state.activeBranch}</h2><p>Usá “Devolver” solamente cuando una atención anterior deba volver a un asesor por indicación del jefe.</p>{currentAssignments.length === 0 ? <p className="round-empty">Todavía no hay asignaciones locales.</p> : <div className="movement-list">{currentAssignments.map(item => <div key={item.id}><strong>{item.advisorName}</strong><span>{item.area} · {item.status}{item.observation && <small className="movement-observation">Observación: {item.observation}</small>}</span><time>{new Date(item.createdAt).toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' })}</time><button className="return-button" onClick={() => { setReturning(item); setReturnAdvisorId(''); setReturnObservation(''); }}>Devolver</button></div>)}</div>}</section>
  </main>;
}
